### ISSUE TITLE
Tests fail during build

### ISSUE THREAD

**Issue by VojislavKovacevic** [execom-eu/OOP-Test-Generator#490]
**Tests fail during build**

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running eu.execom.testgenerator.core.service.category.CategoryServiceImplTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.27 sec - in eu.execom.testgenerator.core.service.category.CategoryServiceImplTest
Running eu.execom.testgenerator.core.service.question.QuestionServiceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec - in eu.execom.testgenerator.core.service.question.QuestionServiceTest
Running eu.execom.testgenerator.core.service.test.ScheduledExpiredTestsHandlerTest
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/vkovacevic/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/vkovacevic/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.109 sec - in eu.execom.testgenerator.core.service.test.ScheduledExpiredTestsHandlerTest
Running eu.execom.testgenerator.core.service.test.TestServiceTest
Tests run: 10, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.752 sec <<< FAILURE! - in eu.execom.testgenerator.core.service.test.TestServiceTest
testApplyReview_whenNotAllReviewed_expectNoAchievedPoints(eu.execom.testgenerator.core.service.test.TestServiceTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NullPointerException: null
        at eu.execom.testgenerator.core.service.test.TestServiceImpl.updateAwardedPoints(TestServiceImpl.java:322)
        at eu.execom.testgenerator.core.service.test.TestServiceImpl.lambda$applyReview$3(TestServiceImpl.java:266)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at eu.execom.testgenerator.core.service.test.TestServiceImpl.applyReview(TestServiceImpl.java:266)
        at eu.execom.testgenerator.core.service.test.TestServiceTest.testApplyReview_whenNotAllReviewed_expectNoAchievedPoints(TestServiceTest.java:304)

testApplyReview_whenAllReviewed_expectAchievedPoints(eu.execom.testgenerator.core.service.test.TestServiceTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException: null
        at eu.execom.testgenerator.core.service.test.TestServiceImpl.updateAwardedPoints(TestServiceImpl.java:322)
        at eu.execom.testgenerator.core.service.test.TestServiceImpl.lambda$applyReview$3(TestServiceImpl.java:266)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at eu.execom.testgenerator.core.service.test.TestServiceImpl.applyReview(TestServiceImpl.java:266)
        at eu.execom.testgenerator.core.service.test.TestServiceTest.testApplyReview_whenAllReviewed_expectAchievedPoints(TestServiceTest.java:253)


Results :

Tests in error:
  TestServiceTest.testApplyReview_whenAllReviewed_expectAchievedPoints:253 » NullPointer
  TestServiceTest.testApplyReview_whenNotAllReviewed_expectNoAchievedPoints:304 » NullPointer

Tests run: 22, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Execom Test Generator 1.0-SNAPSHOT:
[INFO]
[INFO] Execom Test Generator .............................. SUCCESS [  2.610 s]
[INFO] test-generator-core ................................ FAILURE [ 14.778 s]
[INFO] test-generator-web ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.686 s
[INFO] Finished at: 2020-06-15T10:00:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project test-generator-core: There are test failures.
[ERROR]
[ERROR] Please refer to D:\instal\TestGenerator\OOP-Test-Generator-develop(10)\OOP-Test-Generator-develop\core\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
```

**Comment by adamovivan** [comment]
All fixed instead of:

1. TestControllerIntegrationTest:
- shouldGetTestsByUserId
- shouldGetAllTests

2. ReviewControllerTest:
- testGetTestById_whenTestIsNotCompleted_expectConflict
- testGetTestById_whenUserIsNotTestReviewer_expectConflict

... because of bad functionality. 

Pull request: https://github.com/execom-eu/OOP-Test-Generator/pull/504

**Comment by VojislavKovacevic** [comment]
tests fail during the build.
develop branch 7.7.2020.

**LOG**
[logTestsError.txt](https://github.com/execom-eu/OOP-Test-Generator/files/4883444/logTestsError.txt)
